FROM node:20-alpine

RUN mkdir -p /var/www/employee
WORKDIR /var/www/employee
ADD . /var/www/employee
RUN npm install -f
RUN npx nx build employee
EXPOSE 8000
CMD ["node", "./dist/apps/employee/main.js"]