export enum SERVICES {
  AUTH = 'AUTH',
  EMPLOYEE = 'EMPLOYEE',
  LEAVES = 'LEAVES',
  DEPARTMENT = 'DEPARTMENT',
  ATTENDANCE = 'ATTENDANCE',
  ACTIVITY_LOGS = 'ACTIVITY_LOGS',
  PAYROLL = 'PAYROLL',
}